name: Upload artifact
description: MarkText wrapper for actions/upload-artifact@v4.6.2

inputs:
  name:
    description: Artifact name
    required: true
  retention-days:
    description: Days to retain the artifact
    required: false
    default: '30'
  path:
    description: Files or directories to upload
    required: true
  if-no-files-found:
    description: Fail if no files match path
    required: false
    default: error

runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@v4.6.2
      with:
        name: ${{ inputs.name }}
        retention-days: ${{ inputs.retention-days }}
        path: ${{ inputs.path }}
        if-no-files-found: ${{ inputs.if-no-files-found }}
